apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: patient-service
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: patient-service

  endpoints:
    - port: http
      path: /metrics
      interval: 30s

  namespaceSelector:
    matchNames:
      - default