pipeline {
    agent any

    environment {
        PROJECT_ID = "project-e85d8801-bd70-4ddd-8bc"
        REGION = "asia-south1"

        IMAGE_NAME = "patient-service"

        IMAGE_TAG = "${BUILD_NUMBER}"
    }



    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

//        stage('Build Image') {
//            steps {
//                sh """
//                docker build \
//                -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/microservices-repo/${IMAGE_NAME}:${IMAGE_TAG} \
//                .
//                """
//            }
//        }

        stage('Authenticate Artifact Registry') {
            steps {
                sh '''
                gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet
                '''
            }
        }

        stage('Build Image') {
            steps {
                sh """
                docker build \
                -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/microservices-repo/${IMAGE_NAME}:${IMAGE_TAG} \
                -f patient-service/Dockerfile \
                patient-service
                """
            }
        }

        stage('Push Image') {
            steps {
                sh """
                docker push \
                ${REGION}-docker.pkg.dev/${PROJECT_ID}/microservices-repo/${IMAGE_NAME}:${IMAGE_TAG}
                """
            }
        }

//        stage('Update GitOps Repo') {
//            steps {
//                sh '''
//                rm -rf gitops
//
//                git clone https://github.com/YOUR_USERNAME/microservices-gitops.git gitops
//
//                sed -i "s|image:.*|image: asia-south1-docker.pkg.dev/${PROJECT_ID}/microservices-repo/patient-service:${IMAGE_TAG}|g" \
//                gitops/patient-service/deployment.yaml
//
//                cd gitops
//
//                git config user.email "jenkins@local"
//
//                git config user.name "jenkins"
//
//                git add .
//
//                git commit -m "patient-service ${IMAGE_TAG}"
//
//                git push
//                '''
//            }
//        }

        stage('Update Manifest') {
            steps {
                sh """
                git checkout -B main origin/main

                git remote set-url origin git@github.com:Sanjaymavi/hackathon-usecase-hcl.git

                sed -i \
                's#image:.*#image: asia-south1-docker.pkg.dev/${PROJECT_ID}/microservices-repo/patient-service:${BUILD_NUMBER}#' \
                k8s/patient-service/deployment.yaml

                git config user.name "jenkins"
                git config user.email "jenkins@local"

                git add k8s/patient-service/deployment.yaml

                git commit -m "Update patient-service image ${BUILD_NUMBER}"

                git push origin main
                """
            }
        }
    }
}